CREATE TABLE IF NOT EXISTS pipeline_quarantine (
    quarantine_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name VARCHAR(50) NOT NULL,
    batch_id VARCHAR(100) NOT NULL,
    record_index INTEGER NOT NULL CHECK (record_index >= 0),
    raw_record JSONB NOT NULL,
    issue_codes JSONB NOT NULL,
    issue_messages JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pipeline_quarantine_source_batch
    ON pipeline_quarantine (source_name, batch_id);


CREATE TABLE IF NOT EXISTS curated_cases (
    curated_case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    source_name VARCHAR(50) NOT NULL,
    batch_id VARCHAR(100) NOT NULL,

    case_id BIGINT NOT NULL,
    actor_type VARCHAR(20) NOT NULL
        CHECK (actor_type IN ('CUSTOMER', 'VENDOR')),
    actor_id BIGINT NOT NULL
        CHECK (actor_id > 0),

    case_type VARCHAR(30) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,

    category TEXT NOT NULL,
    description TEXT NOT NULL,

    source_created_at TIMESTAMPTZ NOT NULL,
    curated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_curated_case_source_case
        UNIQUE (source_name, case_id)
);

CREATE INDEX IF NOT EXISTS idx_curated_cases_source_batch
    ON curated_cases (source_name, batch_id);

CREATE INDEX IF NOT EXISTS idx_curated_cases_case_type
    ON curated_cases (case_type);